PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS albums (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS photos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_name TEXT UNIQUE,
    rating integer,
    last_displayed INTEGER,
    album_id INTEGER FOREIGN KEY,
    FOREIGN KEY (album_id) REFERENCES album(id) ON DELETE CASCADE
);